base: "BTC"

quotes:
  - "USD"

exchanges:
  - name: "bitfinex2"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/6 * * * * *"
  - name: "ftx"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/2 * * * * *"
  - name: "binance"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USDT"
    provider: "ccxt"
    cron: "*/2 * * * * *"
