files.extend-exclude = [
  "dev",
  "test/postman/*.json",
  "realtime/src/domain/country-to-currency/index.ts"
]

[default.extend-words]
# returned from twilio API referenced in src/debug/text-sms.ts
Ons = "Ons"
