receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  attributes:
    actions:
    - key: apiKey
      action: update
      value: "<redacted>"
    - key: access_key
      action: update
      value: "<redacted>"

exporters:
  logging:
    verbosity: Detailed
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": ${HONEYCOMB_DATASET}

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes, batch]
      exporters: [otlp, logging]
