FROM node:18-alpine

WORKDIR /app
COPY ./history/src/config/process.ts ./history/src/config/database.ts ./
COPY ./history/src/config/database ./database
COPY ./history/scripts ./scripts

RUN yarn add knex@1.0.3 pg@8.7.3 typescript@4.5.5 ts-node@10.5.0 @types/node@16.11.7

USER 1000

ARG BUILDTIME
ARG COMMITHASH
ENV BUILDTIME ${BUILDTIME}
ENV COMMITHASH ${COMMITHASH}

ENTRYPOINT ["scripts/migrate.sh"]
