base: "BTC"

# the default is the first currency
quotes:
  - { code: "USD", symbol: "$", name: "US Dollar", flag: "🇺🇸" }

exchanges:
  - name: "bitfinex2"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/10 * * * * *"
  - name: "okcoin"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/15 * * * * *"
  - name: "binanceus"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/5 * * * * *"
  - name: "exchangeratesapi"
    enabled: false
    quoteAlias: "CRC"
    base: "USD"
    quote: "CRC"
    provider: "exchangeratesapi"
    cron: "*/5 * * * * *"
    config:
      baseUrl: "http://api.exchangeratesapi.io/v1"
      apiKey: "<your api key>"
      cacheSeconds: 14400
