base: "BTC"

# the default is the first currency
quotes:
  - { code: "USD", symbol: "$", name: "US Dollar", flag: "🇺🇸" }
  - { code: "EUR", symbol: "€", name: "Euro", flag: "🇪🇺" }

exchanges:
  - name: "bitfinex2"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/10 * * * * *"
  - name: "okcoin"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/15 * * * * *"
  - name: "binanceus"
    enabled: true
    quoteAlias: "USD"
    base: "BTC"
    quote: "USD"
    provider: "ccxt"
    cron: "*/5 * * * * *"
  - name: "free-currency-rates-usd"
    enabled: true
    quoteAlias: "*"
    base: "USD"
    quote: "*"
    provider: "free-currency-rates"
    cron: "*/5 * * * * *"
    config:
      baseUrl: "https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/"
      fallbackUrl: "https://raw.githubusercontent.com/fawazahmed0/currency-api/1/latest/currencies/"
      cacheSeconds: 1800
  - name: "currencybeacon"
    enabled: false
    quoteAlias: "*"
    base: "USD"
    quote: "*"
    provider: "currencybeacon"
    cron: "*/5 * * * * *"
    config:
      baseUrl: "https://api.currencybeacon.com/v1"
      apiKey: "<your api key>"
      cacheSeconds: 900
  - name: "exchangeratesapi"
    enabled: false
    quoteAlias: "CRC"
    base: "USD"
    quote: "CRC"
    provider: "exchangeratesapi"
    cron: "*/5 * * * * *"
    config:
      baseUrl: "http://api.exchangeratesapi.io/v1"
      apiKey: "<your api key>"
      cacheSeconds: 14400
