name: "History Unit test"
on:
  pull_request:
    branches: [ main ]
    paths:
      - "Makefile"
      - "*.json"
      - "history/**"
jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - name: Run unit tests
      run: make history-unit-in-ci
