name: "Realtime Unit test"
on:
  pull_request:
    branches: [ main ]
    paths:
      - "realtime/**"
jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - name: Run unit tests
      working-directory: ./realtime
      run: make unit-in-ci
